:art: Cleaned up unnecessary spacing

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
-set -eu
-[ "${BASH_VERSINFO[0]}" -ge 3 ] && set -o pipefail
+
+set -e
+set -o pipefail
+
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
 get_platform () {
 	local platform="$(uname | tr '[:upper:]' '[:lower:]')"
@@ -40,7 +44,6 @@ get_download_url () {
 	local version=$1
 	local platform=$2
 	local arch=$3
-
 	echo "https://storage.googleapis.com/golang/go${version}.${platform}-${arch}.tar.gz"
 }
 
@@ -64,9 +67,7 @@ install_golang () {
 		local download_url=$(get_download_url $version $platform $arch)
 
     curl $download_url -o "${tempdir}/archive.tar.gz"
-
     tar -C "$install_path" -xzf "${tempdir}/archive.tar.gz"
-
     rm -rf "${tempdir}"
 }
 
